[package]
name = "sqrit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket="0.4"
uuid={version="0.8", features=["v4"]}
qr_code = {version="1.1.0", features=["bmp"]}
